services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agent_runner
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
